### ISSUE TITLE
err: DomainException: Unable to map device mode from mode

### ISSUE THREAD

**Issue by vicampuzano** [congatudo/congatudo-add-on#31]
I started getting this error after cleaning my house:

```
[2022-03-30T13:12:31.518Z] [ERROR] Uncaught Exception {
  err: DomainException: Unable to map device mode from mode 39
      at getDomainValue (/snapshot/app/node_modules/@agnoc/core/lib/mappers/device-mode.mapper.js:35:9)
      at Function.toDomain (/snapshot/app/node_modules/@agnoc/core/lib/mappers/device-mode.mapper.js:41:14)
      at Robot.handleMapUpdate (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:910:59)
      at Robot.handleMessage (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1142:7)
      at CloudServer.handleMessage (/snapshot/app/node_modules/@agnoc/core/lib/emitters/cloud-server.emitter.js:135:13)
      at Connection.<anonymous> (/snapshot/app/node_modules/@agnoc/core/lib/emitters/cloud-server.emitter.js:154:12)
      at Connection.emit (node:events:402:35)
      at Connection.handlePacket (/snapshot/app/node_modules/@agnoc/core/lib/emitters/connection.emitter.js:114:10)
      at PacketSocket.emit (node:events:390:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at PacketSocket.Readable.push (node:internal/streams/readable:228:10)
      at PacketSocket.onReadable (/snapshot/app/node_modules/@agnoc/core/lib/sockets/packet.socket.js:130:27)
      at processImmediate (node:internal/timers:464:21) {
    metadata: undefined
  },
  origin: 'uncaughtException'
}
```

**Comment by ciltocruz** [comment]
Same for me, but mode 38.

```
[2022-06-20T09:51:50.674Z] [ERROR] Uncaught Exception {
  err: DomainException: Unable to map device mode from mode 38
      at getDomainValue (/snapshot/app/node_modules/@agnoc/core/lib/mappers/device-mode.mapper.js:35:9)
      at Function.toDomain (/snapshot/app/node_modules/@agnoc/core/lib/mappers/device-mode.mapper.js:41:14)
      at Robot.handleDeviceStatus (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:863:57)
      at Robot.handleMessage (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1142:7)
      at CloudServer.handleMessage (/snapshot/app/node_modules/@agnoc/core/lib/emitters/cloud-server.emitter.js:135:13)
      at Connection.<anonymous> (/snapshot/app/node_modules/@agnoc/core/lib/emitters/cloud-server.emitter.js:154:12)
      at Connection.emit (node:events:406:35)
      at Connection.handlePacket (/snapshot/app/node_modules/@agnoc/core/lib/emitters/connection.emitter.js:114:10)
      at PacketSocket.emit (node:events:394:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at PacketSocket.Readable.push (node:internal/streams/readable:228:10)
      at PacketSocket.onReadable (/snapshot/app/node_modules/@agnoc/core/lib/sockets/packet.socket.js:130:27)
      at processImmediate (node:internal/timers:464:21) {
    metadata: undefined
  },
[2022-06-20T09:51:50.675Z] [INFO] Valetudo shutdown in progress...
[2022-06-20T09:51:50.676Z] [DEBUG] NetworkAdvertisementManager shutdown in progress...
[2022-06-20T09:51:50.676Z] [DEBUG] NetworkAdvertisementManager shutdown done
[2022-06-20T09:51:50.677Z] [DEBUG] Scheduler shutdown in progress...
[2022-06-20T09:51:50.677Z] [DEBUG] Scheduler shutdown done
  origin: 'uncaughtException'
}
```

**Comment by Snakesms** [comment]
Got mode 39 error today on conga 3690 (if the model does matter)

**Comment by elraro** [comment]
Please, try the beta addon.

If you still have problems, open a issue in agnoc repository: https://github.com/congatudo/agnoc
