### ISSUE TITLE
Web UI does not start

### ISSUE THREAD

**Issue by erpayo** [congatudo/congatudo-add-on#53]
Web UI is not starting. When clicking at Congatudo option in sidebar menu nothing is displayed.
Valetudo map card work fine, showing the map and I'm able to control the robot: clean, return to dock, locate, etc.
Robot model: Conga 3690

Logs at init:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[20:22:23] INFO: Using configuration from '/config/valetudo.json'...
[2023-11-08T19:22:49.613Z] [INFO] Loading configuration file: /config/valetudo.json
[2023-11-08T19:22:52.499Z] [INFO] Set Logfile to /tmp/valetudo.log
[2023-11-08T19:22:52.635Z] [INFO] Starting Valetudo 2023.05
[2023-11-08T19:22:52.647Z] [INFO] Commit ID: 093d853701a06a4d07aa494c7b84650cb9ea2f3e
[2023-11-08T19:22:52.651Z] [INFO] Configuration file: /config/valetudo.json
[2023-11-08T19:22:52.659Z] [INFO] Logfile: /tmp/valetudo.log
[2023-11-08T19:22:52.662Z] [INFO] Robot: Cecotec Conga (CecotecCongaRobot)
[2023-11-08T19:22:52.663Z] [INFO] JS Runtime Version: v18.12.1-Valetudo
[2023-11-08T19:22:52.665Z] [INFO] Arch: arm64
[2023-11-08T19:22:52.684Z] [INFO] Max Heap Size: 64 MiB
[2023-11-08T19:22:52.688Z] [INFO] Node Flags: --expose-gc --max-heap-size=64
[2023-11-08T19:22:52.747Z] [INFO] Autogenerated System ID: LawfulInsecureChicken
[2023-11-08T19:23:13.029Z] [INFO] Webserver running on port 8080
[2023-11-08T19:23:14.429Z] [INFO] Added new robot with id '12545'
[2023-11-08T19:23:15.616Z] [INFO] Connected successfully to MQTT broker
[2023-11-08T19:23:17.918Z] [INFO] MQTT configured
``` 

When stopping this is the log. There is an ERR_SERVER_NOT_RUNNING. Tried to set a different port in Configuration tab for the web UI, but it still says 8080 at startup

```
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[2023-11-08T19:22:07.413Z] [INFO] Valetudo shutdown in progress...
[2023-11-08T19:22:07.562Z] [INFO] Valetudo shutdown in progress...
[2023-11-08T19:22:07.565Z] [INFO] Valetudo shutdown in progress...
[2023-11-08T19:22:07.688Z] [INFO] Disconnecting from the MQTT Broker...
[2023-11-08T19:22:07.708Z] [INFO] Disconnecting from the MQTT Broker...
[2023-11-08T19:22:07.720Z] [INFO] Disconnecting from the MQTT Broker...
[2023-11-08T19:22:07.835Z] [INFO] Successfully disconnected from the MQTT Broker
[2023-11-08T19:22:07.836Z] [INFO] Successfully disconnected from the MQTT Broker
[2023-11-08T19:22:07.837Z] [INFO] Successfully disconnected from the MQTT Broker
[2023-11-08T19:22:07.902Z] [ERROR] Error occured:  Error  -  Server is not running.
[2023-11-08T19:22:07.937Z] [ERROR] Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (node:internal/errors:393:5)
    at Server.close (node:net:1827:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:525:35)
    at emitCloseNT (node:net:1880:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
[2023-11-08T19:22:07.942Z] [ERROR] Stacktrace that lead to the process exiting with code 1: Error
    at process.<anonymous> (/snapshot/app/backend/index.js:58:93)
    at process.emit (node:events:513:28)
    at process.exit (node:internal/process/per_thread:190:15)
    at process.shutdown (/snapshot/app/backend/index.js:33:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by erpayo** [comment]
some hours later the issue resolved itself. Web UI starts fine.
